apiVersion: v1
kind: Service
metadata:
  name: spring-boot-app-service
spec:
  type: NodePort
  selector:
    app: spring-boot-app-service
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
